### ISSUE TITLE
Release fails because of snapshots

### ISSUE THREAD

**Issue by fredrikstave** [rocjs/roc-repo#13]
### What happened?
When I try to release a component, the tests fail when I have made changes to the component AND there's an existing `__snapshots__` folder present.

### What was expected?
The `__snapshots__` should be removed between releases.

### How to reproduce?
Create a component with a known error (like an assumed object prop `theme` in my case), then try to release. When the tests fail, fix your mistake, then commit and try to release again.

Now the tests will fail (see console output below).

I'm running `roc@1.0.0-rc.23`, `roc-plugin-repo-react@~0.0.4` and `roc-plugin-repo@~0.0.19`.
```
 ✔ Building
 ✖ Testing
   → Found a local version of Roc, will use that over the global one.
   Prepare for release
   Publishing to npm
   Pushing to remote
   Creating GitHub release
⚠ A problem occurred when running the command

Command failed: /bin/sh -c roc repo test @e24/ui-list
 FAIL  components/ui-list/src/UiList.spec.js
  ● UiList › renders correctly

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received
```

**Comment by dlmr** [comment]
Thanks for the bug report!

The recommendation is to commit the `__snapshots__` directory into git, are you doing that here?

**Comment by fredrikstave** [comment]
Thank you for the quick response!
I haven't committed the `__snapshots__` folder. Will start doing it 👍
